//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressStateInfo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressStateInfo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="2"/&gt;
 *     &lt;enumeration value="JA"/&gt;
 *     &lt;enumeration value="AL"/&gt;
 *     &lt;enumeration value="AK"/&gt;
 *     &lt;enumeration value="AZ"/&gt;
 *     &lt;enumeration value="AR"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="CT"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="FL"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="HI"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="IL"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="IA"/&gt;
 *     &lt;enumeration value="KS"/&gt;
 *     &lt;enumeration value="KY"/&gt;
 *     &lt;enumeration value="LA"/&gt;
 *     &lt;enumeration value="ME"/&gt;
 *     &lt;enumeration value="MD"/&gt;
 *     &lt;enumeration value="MA"/&gt;
 *     &lt;enumeration value="MI"/&gt;
 *     &lt;enumeration value="MN"/&gt;
 *     &lt;enumeration value="MS"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="NE"/&gt;
 *     &lt;enumeration value="NV"/&gt;
 *     &lt;enumeration value="NH"/&gt;
 *     &lt;enumeration value="NJ"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *     &lt;enumeration value="NY"/&gt;
 *     &lt;enumeration value="NC"/&gt;
 *     &lt;enumeration value="ND"/&gt;
 *     &lt;enumeration value="OH"/&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="RI"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="TN"/&gt;
 *     &lt;enumeration value="TX"/&gt;
 *     &lt;enumeration value="UT"/&gt;
 *     &lt;enumeration value="VT"/&gt;
 *     &lt;enumeration value="VA"/&gt;
 *     &lt;enumeration value="WA"/&gt;
 *     &lt;enumeration value="WV"/&gt;
 *     &lt;enumeration value="WI"/&gt;
 *     &lt;enumeration value="WY"/&gt;
 *     &lt;enumeration value="AB"/&gt;
 *     &lt;enumeration value="BC"/&gt;
 *     &lt;enumeration value="DR"/&gt;
 *     &lt;enumeration value="MB"/&gt;
 *     &lt;enumeration value="MX"/&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="NF"/&gt;
 *     &lt;enumeration value="NS"/&gt;
 *     &lt;enumeration value="ON"/&gt;
 *     &lt;enumeration value="PE"/&gt;
 *     &lt;enumeration value="PQ"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="SK"/&gt;
 *     &lt;enumeration value="VI"/&gt;
 *     &lt;enumeration value="DF"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *     &lt;enumeration value="GT"/&gt;
 *     &lt;enumeration value="PU"/&gt;
 *     &lt;enumeration value="YA"/&gt;
 *     &lt;enumeration value="SN"/&gt;
 *     &lt;enumeration value="BA"/&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="CL"/&gt;
 *     &lt;enumeration value="AA"/&gt;
 *     &lt;enumeration value="BI"/&gt;
 *     &lt;enumeration value="PB"/&gt;
 *     &lt;enumeration value="AG"/&gt;
 *     &lt;enumeration value="BN"/&gt;
 *     &lt;enumeration value="CI"/&gt;
 *     &lt;enumeration value="CP"/&gt;
 *     &lt;enumeration value="CS"/&gt;
 *     &lt;enumeration value="DU"/&gt;
 *     &lt;enumeration value="GJ"/&gt;
 *     &lt;enumeration value="GR"/&gt;
 *     &lt;enumeration value="HD"/&gt;
 *     &lt;enumeration value="HK"/&gt;
 *     &lt;enumeration value="MC"/&gt;
 *     &lt;enumeration value="MR"/&gt;
 *     &lt;enumeration value="NL"/&gt;
 *     &lt;enumeration value="NZ"/&gt;
 *     &lt;enumeration value="OX"/&gt;
 *     &lt;enumeration value="QT"/&gt;
 *     &lt;enumeration value="QR"/&gt;
 *     &lt;enumeration value="SL"/&gt;
 *     &lt;enumeration value="SO"/&gt;
 *     &lt;enumeration value="TA"/&gt;
 *     &lt;enumeration value="TB"/&gt;
 *     &lt;enumeration value="TL"/&gt;
 *     &lt;enumeration value="VE"/&gt;
 *     &lt;enumeration value="YC"/&gt;
 *     &lt;enumeration value="ZA"/&gt;
 *     &lt;enumeration value="ZZ"/&gt;
 *     &lt;enumeration value="AE"/&gt;
 *     &lt;enumeration value="BE"/&gt;
 *     &lt;enumeration value="YT"/&gt;
 *     &lt;enumeration value="AS"/&gt;
 *     &lt;enumeration value="FM"/&gt;
 *     &lt;enumeration value="GM"/&gt;
 *     &lt;enumeration value="MH"/&gt;
 *     &lt;enumeration value="NO"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="UM"/&gt;
 *     &lt;enumeration value="VZ"/&gt;
 *     &lt;enumeration value="CE"/&gt;
 *     &lt;enumeration value="CR"/&gt;
 *     &lt;enumeration value="LM"/&gt;
 *     &lt;enumeration value="TE"/&gt;
 *     &lt;enumeration value="FS"/&gt;
 *     &lt;enumeration value="FN"/&gt;
 *     &lt;enumeration value="CN"/&gt;
 *     &lt;enumeration value="GU"/&gt;
 *     &lt;enumeration value="MP"/&gt;
 *     &lt;enumeration value="PW"/&gt;
 *     &lt;enumeration value="NT"/&gt;
 *     &lt;enumeration value="NU"/&gt;
 *     &lt;enumeration value="QC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AddressStateInfo")
@XmlEnum
public enum AddressStateInfo {

    JA,
    AL,
    AK,
    AZ,
    AR,
    CA,
    CO,
    CT,
    DE,
    DC,
    FL,
    GA,
    HI,
    ID,
    IL,
    IN,
    IA,
    KS,
    KY,
    LA,
    ME,
    MD,
    MA,
    MI,
    MN,
    MS,
    MO,
    MT,
    NE,
    NV,
    NH,
    NJ,
    NM,
    NY,
    NC,
    ND,
    OH,
    OK,
    OR,
    PA,
    RI,
    SC,
    SD,
    TN,
    TX,
    UT,
    VT,
    VA,
    WA,
    WV,
    WI,
    WY,
    AB,
    BC,
    DR,
    MB,
    MX,
    NB,
    NF,
    NS,
    ON,
    PE,
    PQ,
    PR,
    SK,
    VI,
    DF,
    NA,
    GT,
    PU,
    YA,
    SN,
    BA,
    AP,
    CL,
    AA,
    BI,
    PB,
    AG,
    BN,
    CI,
    CP,
    CS,
    DU,
    GJ,
    GR,
    HD,
    HK,
    MC,
    MR,
    NL,
    NZ,
    OX,
    QT,
    QR,
    SL,
    SO,
    TA,
    TB,
    TL,
    VE,
    YC,
    ZA,
    ZZ,
    AE,
    BE,
    YT,
    AS,
    FM,
    GM,
    MH,
    NO,
    PL,
    UM,
    VZ,
    CE,
    CR,
    LM,
    TE,
    FS,
    FN,
    CN,
    GU,
    MP,
    PW,
    NT,
    NU,
    QC;

    public String value() {
        return name();
    }

    public static AddressStateInfo fromValue(String v) {
        return valueOf(v);
    }

}
