//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * This type TB bandwidth profile data
 * 
 * <p>Java class for BandwidthProfileDataInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BandwidthProfileDataInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="networkTransportType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceNetworkTypeInfo" minOccurs="0"/&gt;
 *         &lt;element name="frequency17MHzIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="vectoringIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="setProfileIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="profileName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BandwidthProfileDataInfo", propOrder = {
    "networkTransportType",
    "frequency17MHzIndicator",
    "vectoringIndicator",
    "setProfileIndicator",
    "profileName",
    "totalBandwidth"
})
public class BandwidthProfileDataInfo {

    protected String networkTransportType;
    protected Boolean frequency17MHzIndicator;
    protected Boolean vectoringIndicator;
    protected Boolean setProfileIndicator;
    protected String profileName;
    @XmlElement(name = "TotalBandwidth")
    protected List<NetworkTransportBandwidthInfo> totalBandwidth;

    /**
     * Gets the value of the networkTransportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkTransportType() {
        return networkTransportType;
    }

    /**
     * Sets the value of the networkTransportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkTransportType(String value) {
        this.networkTransportType = value;
    }

    /**
     * Gets the value of the frequency17MHzIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFrequency17MHzIndicator() {
        return frequency17MHzIndicator;
    }

    /**
     * Sets the value of the frequency17MHzIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFrequency17MHzIndicator(Boolean value) {
        this.frequency17MHzIndicator = value;
    }

    /**
     * Gets the value of the vectoringIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVectoringIndicator() {
        return vectoringIndicator;
    }

    /**
     * Sets the value of the vectoringIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVectoringIndicator(Boolean value) {
        this.vectoringIndicator = value;
    }

    /**
     * Gets the value of the setProfileIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSetProfileIndicator() {
        return setProfileIndicator;
    }

    /**
     * Sets the value of the setProfileIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSetProfileIndicator(Boolean value) {
        this.setProfileIndicator = value;
    }

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the totalBandwidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalBandwidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalBandwidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkTransportBandwidthInfo }
     * 
     * 
     */
    public List<NetworkTransportBandwidthInfo> getTotalBandwidth() {
        if (totalBandwidth == null) {
            totalBandwidth = new ArrayList<NetworkTransportBandwidthInfo>();
        }
        return this.totalBandwidth;
    }

}
