//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiberServiceProductTypeInfo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FiberServiceProductTypeInfo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LIGHTSPEED"/&gt;
 *     &lt;enumeration value="IPTV"/&gt;
 *     &lt;enumeration value="VOIP"/&gt;
 *     &lt;enumeration value="HSIA"/&gt;
 *     &lt;enumeration value="HSIALOW"/&gt;
 *     &lt;enumeration value="HSIAMED"/&gt;
 *     &lt;enumeration value="HSIAHIGH"/&gt;
 *     &lt;enumeration value="ADSL"/&gt;
 *     &lt;enumeration value="SATELLITE"/&gt;
 *     &lt;enumeration value="WIRELESS"/&gt;
 *     &lt;enumeration value="DTV"/&gt;
 *     &lt;enumeration value="FBS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FiberServiceProductTypeInfo")
@XmlEnum
public enum FiberServiceProductTypeInfo {

    LIGHTSPEED,
    IPTV,
    VOIP,
    HSIA,
    HSIALOW,
    HSIAMED,
    HSIAHIGH,
    ADSL,
    SATELLITE,
    WIRELESS,
    DTV,
    FBS;

    public String value() {
        return name();
    }

    public static FiberServiceProductTypeInfo fromValue(String v) {
        return valueOf(v);
    }

}
