//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiberServiceBandwidthConnectivitySourceInfo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FiberServiceBandwidthConnectivitySourceInfo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CO_NBR"/&gt;
 *     &lt;enumeration value="CO_PBR"/&gt;
 *     &lt;enumeration value="CSI"/&gt;
 *     &lt;enumeration value="FTI"/&gt;
 *     &lt;enumeration value="MABR"/&gt;
 *     &lt;enumeration value="RT_NBR"/&gt;
 *     &lt;enumeration value="RT_PBR"/&gt;
 *     &lt;enumeration value="MIN"/&gt;
 *     &lt;enumeration value="MAX"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FiberServiceBandwidthConnectivitySourceInfo")
@XmlEnum
public enum FiberServiceBandwidthConnectivitySourceInfo {

    CO_NBR,
    CO_PBR,
    CSI,
    FTI,
    MABR,
    RT_NBR,
    RT_PBR,
    MIN,
    MAX;

    public String value() {
        return name();
    }

    public static FiberServiceBandwidthConnectivitySourceInfo fromValue(String v) {
        return valueOf(v);
    }

}
