//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * This type identifies a location where one or more network transport types are identified and for each transport one or more fiber based products may be available.
 * 
 * <p>Java class for FiberServiceLocationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiberServiceLocationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NetworkTransport" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ValidatedAddress" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceAddressInfo"/&gt;
 *         &lt;element name="connectedCommunityIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="whpEligibleIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="migrationTargetIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Product" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceProductQualificationInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="convergedBillingIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="titanExistingIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="titanPendingIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="tariffGeographyCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}SBSTariffGeographyCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="fccWireCenterStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="outOfEMTCapacityIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="estimatedCompletionDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithoutTimezoneInfo" minOccurs="0"/&gt;
 *         &lt;element name="singleDispatchIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="gigaPowerAvailabilityIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="abfGPONIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ovalsPropertyId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ovalsBuildingId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiberServiceLocationInfo", propOrder = {
    "networkTransport",
    "validatedAddress",
    "connectedCommunityIndicator",
    "whpEligibleIndicator",
    "migrationTargetIdentifier",
    "product",
    "convergedBillingIndicator",
    "titanExistingIndicator",
    "titanPendingIndicator",
    "tariffGeographyCode",
    "fccWireCenterStatus",
    "outOfEMTCapacityIndicator",
    "estimatedCompletionDate",
    "singleDispatchIndicator",
    "gigaPowerAvailabilityIndicator",
    "abfGPONIndicator",
    "ovalsPropertyId",
    "ovalsBuildingId"
})
public class FiberServiceLocationInfo {

    @XmlElement(name = "NetworkTransport")
    protected List<NetworkTransportInfo> networkTransport;
    @XmlElement(name = "ValidatedAddress", required = true)
    protected FiberServiceAddressInfo validatedAddress;
    protected boolean connectedCommunityIndicator;
    protected Boolean whpEligibleIndicator;
    protected String migrationTargetIdentifier;
    @XmlElement(name = "Product")
    protected List<FiberServiceProductQualificationInfo> product;
    protected Boolean convergedBillingIndicator;
    protected Boolean titanExistingIndicator;
    protected Boolean titanPendingIndicator;
    @XmlSchemaType(name = "string")
    protected SBSTariffGeographyCodeInfo tariffGeographyCode;
    protected String fccWireCenterStatus;
    protected Boolean outOfEMTCapacityIndicator;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar estimatedCompletionDate;
    protected Boolean singleDispatchIndicator;
    protected Boolean gigaPowerAvailabilityIndicator;
    protected Boolean abfGPONIndicator;
    protected String ovalsPropertyId;
    protected String ovalsBuildingId;

    /**
     * Gets the value of the networkTransport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkTransport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkTransport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkTransportInfo }
     * 
     * 
     */
    public List<NetworkTransportInfo> getNetworkTransport() {
        if (networkTransport == null) {
            networkTransport = new ArrayList<NetworkTransportInfo>();
        }
        return this.networkTransport;
    }

    /**
     * Gets the value of the validatedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FiberServiceAddressInfo }
     *     
     */
    public FiberServiceAddressInfo getValidatedAddress() {
        return validatedAddress;
    }

    /**
     * Sets the value of the validatedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberServiceAddressInfo }
     *     
     */
    public void setValidatedAddress(FiberServiceAddressInfo value) {
        this.validatedAddress = value;
    }

    /**
     * Gets the value of the connectedCommunityIndicator property.
     * 
     */
    public boolean isConnectedCommunityIndicator() {
        return connectedCommunityIndicator;
    }

    /**
     * Sets the value of the connectedCommunityIndicator property.
     * 
     */
    public void setConnectedCommunityIndicator(boolean value) {
        this.connectedCommunityIndicator = value;
    }

    /**
     * Gets the value of the whpEligibleIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWhpEligibleIndicator() {
        return whpEligibleIndicator;
    }

    /**
     * Sets the value of the whpEligibleIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWhpEligibleIndicator(Boolean value) {
        this.whpEligibleIndicator = value;
    }

    /**
     * Gets the value of the migrationTargetIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMigrationTargetIdentifier() {
        return migrationTargetIdentifier;
    }

    /**
     * Sets the value of the migrationTargetIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMigrationTargetIdentifier(String value) {
        this.migrationTargetIdentifier = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FiberServiceProductQualificationInfo }
     * 
     * 
     */
    public List<FiberServiceProductQualificationInfo> getProduct() {
        if (product == null) {
            product = new ArrayList<FiberServiceProductQualificationInfo>();
        }
        return this.product;
    }

    /**
     * Gets the value of the convergedBillingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConvergedBillingIndicator() {
        return convergedBillingIndicator;
    }

    /**
     * Sets the value of the convergedBillingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConvergedBillingIndicator(Boolean value) {
        this.convergedBillingIndicator = value;
    }

    /**
     * Gets the value of the titanExistingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTitanExistingIndicator() {
        return titanExistingIndicator;
    }

    /**
     * Sets the value of the titanExistingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTitanExistingIndicator(Boolean value) {
        this.titanExistingIndicator = value;
    }

    /**
     * Gets the value of the titanPendingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTitanPendingIndicator() {
        return titanPendingIndicator;
    }

    /**
     * Sets the value of the titanPendingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTitanPendingIndicator(Boolean value) {
        this.titanPendingIndicator = value;
    }

    /**
     * Gets the value of the tariffGeographyCode property.
     * 
     * @return
     *     possible object is
     *     {@link SBSTariffGeographyCodeInfo }
     *     
     */
    public SBSTariffGeographyCodeInfo getTariffGeographyCode() {
        return tariffGeographyCode;
    }

    /**
     * Sets the value of the tariffGeographyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBSTariffGeographyCodeInfo }
     *     
     */
    public void setTariffGeographyCode(SBSTariffGeographyCodeInfo value) {
        this.tariffGeographyCode = value;
    }

    /**
     * Gets the value of the fccWireCenterStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFccWireCenterStatus() {
        return fccWireCenterStatus;
    }

    /**
     * Sets the value of the fccWireCenterStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFccWireCenterStatus(String value) {
        this.fccWireCenterStatus = value;
    }

    /**
     * Gets the value of the outOfEMTCapacityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOutOfEMTCapacityIndicator() {
        return outOfEMTCapacityIndicator;
    }

    /**
     * Sets the value of the outOfEMTCapacityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOutOfEMTCapacityIndicator(Boolean value) {
        this.outOfEMTCapacityIndicator = value;
    }

    /**
     * Gets the value of the estimatedCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedCompletionDate() {
        return estimatedCompletionDate;
    }

    /**
     * Sets the value of the estimatedCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedCompletionDate(XMLGregorianCalendar value) {
        this.estimatedCompletionDate = value;
    }

    /**
     * Gets the value of the singleDispatchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSingleDispatchIndicator() {
        return singleDispatchIndicator;
    }

    /**
     * Sets the value of the singleDispatchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleDispatchIndicator(Boolean value) {
        this.singleDispatchIndicator = value;
    }

    /**
     * Gets the value of the gigaPowerAvailabilityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGigaPowerAvailabilityIndicator() {
        return gigaPowerAvailabilityIndicator;
    }

    /**
     * Sets the value of the gigaPowerAvailabilityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGigaPowerAvailabilityIndicator(Boolean value) {
        this.gigaPowerAvailabilityIndicator = value;
    }

    /**
     * Gets the value of the abfGPONIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbfGPONIndicator() {
        return abfGPONIndicator;
    }

    /**
     * Sets the value of the abfGPONIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbfGPONIndicator(Boolean value) {
        this.abfGPONIndicator = value;
    }

    /**
     * Gets the value of the ovalsPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvalsPropertyId() {
        return ovalsPropertyId;
    }

    /**
     * Sets the value of the ovalsPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvalsPropertyId(String value) {
        this.ovalsPropertyId = value;
    }

    /**
     * Gets the value of the ovalsBuildingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvalsBuildingId() {
        return ovalsBuildingId;
    }

    /**
     * Sets the value of the ovalsBuildingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvalsBuildingId(String value) {
        this.ovalsBuildingId = value;
    }

}
