//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FiberServiceAddressInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiberServiceAddressInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FieldedAddress"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressUnrestrictedInfo"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ruralAddressAttention" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressLineInfo" minOccurs="0"/&gt;
 *                   &lt;element name="addressSubType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressTypeInfo" minOccurs="0"/&gt;
 *                   &lt;element name="internationalAddressLine" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="255"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="internationalZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cassAddress" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CassAddressInfo" minOccurs="0"/&gt;
 *         &lt;element name="lastUpdatedAddress" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateTimeWithTimezoneInfo" minOccurs="0"/&gt;
 *         &lt;element name="rateZoneBanCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="geoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="addressMatchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="disconnectDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
 *         &lt;element name="siteId" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressId" minOccurs="0"/&gt;
 *         &lt;element name="siteAddrId" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressId" minOccurs="0"/&gt;
 *         &lt;element name="addressId" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressId" minOccurs="0"/&gt;
 *         &lt;element name="legalEntity" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}LegalEntityInfo" minOccurs="0"/&gt;
 *         &lt;element name="buildingType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressUnitInfo" minOccurs="0"/&gt;
 *         &lt;element name="tarCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TaxCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="rateCenterCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}RateCenterCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="exchangeCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}ExchangeCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="primaryNpaNxx" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}PhoneNpaNxxInfo" minOccurs="0"/&gt;
 *         &lt;element name="clli8" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI8Info" minOccurs="0"/&gt;
 *         &lt;element name="linkKey" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}LinkKeyInfo" minOccurs="0"/&gt;
 *         &lt;element name="telephoneNumber" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TelephoneNumberInfo" minOccurs="0"/&gt;
 *         &lt;element name="lastDisconnectedTransportType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceNetworkTypeInfo" minOccurs="0"/&gt;
 *         &lt;element name="lastNADType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceNADTypeInfo" minOccurs="0"/&gt;
 *         &lt;element name="videoHubOffice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="smartMoves" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="exhaustCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceExhaustCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="fttbBuildingClli" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI11Info" minOccurs="0"/&gt;
 *         &lt;element name="t1Indicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="cpeRequiredIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="convertedIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="servingAreaDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="circuitId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}WirelineCircuitIdInfo"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fttxConversionIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiberServiceAddressInfo", propOrder = {
    "fieldedAddress",
    "cassAddress",
    "lastUpdatedAddress",
    "rateZoneBanCode",
    "geoCode",
    "addressMatchCode",
    "disconnectDate",
    "siteId",
    "siteAddrId",
    "addressId",
    "legalEntity",
    "buildingType",
    "tarCode",
    "rateCenterCode",
    "exchangeCode",
    "primaryNpaNxx",
    "clli8",
    "linkKey",
    "telephoneNumber",
    "lastDisconnectedTransportType",
    "lastNADType",
    "videoHubOffice",
    "smartMoves",
    "exhaustCode",
    "fttbBuildingClli",
    "t1Indicator",
    "cpeRequiredIndicator",
    "convertedIndicator",
    "servingAreaDescription",
    "circuitId",
    "fttxConversionIndicator"
})
public class FiberServiceAddressInfo {

    @XmlElement(name = "FieldedAddress", required = true)
    protected FieldedAddress fieldedAddress;
    protected CassAddressInfo cassAddress;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedAddress;
    protected String rateZoneBanCode;
    protected String geoCode;
    protected String addressMatchCode;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar disconnectDate;
    protected String siteId;
    protected String siteAddrId;
    protected String addressId;
    protected String legalEntity;
    protected String buildingType;
    protected String tarCode;
    protected String rateCenterCode;
    protected String exchangeCode;
    protected String primaryNpaNxx;
    protected String clli8;
    @XmlSchemaType(name = "string")
    protected LinkKeyInfo linkKey;
    protected String telephoneNumber;
    protected String lastDisconnectedTransportType;
    @XmlSchemaType(name = "string")
    protected FiberServiceNADTypeInfo lastNADType;
    protected String videoHubOffice;
    protected String smartMoves;
    @XmlSchemaType(name = "string")
    protected FiberServiceExhaustCodeInfo exhaustCode;
    protected String fttbBuildingClli;
    protected Boolean t1Indicator;
    protected Boolean cpeRequiredIndicator;
    protected Boolean convertedIndicator;
    protected String servingAreaDescription;
    protected String circuitId;
    protected Boolean fttxConversionIndicator;

    /**
     * Gets the value of the fieldedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FieldedAddress }
     *     
     */
    public FieldedAddress getFieldedAddress() {
        return fieldedAddress;
    }

    /**
     * Sets the value of the fieldedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldedAddress }
     *     
     */
    public void setFieldedAddress(FieldedAddress value) {
        this.fieldedAddress = value;
    }

    /**
     * Gets the value of the cassAddress property.
     * 
     * @return
     *     possible object is
     *     {@link CassAddressInfo }
     *     
     */
    public CassAddressInfo getCassAddress() {
        return cassAddress;
    }

    /**
     * Sets the value of the cassAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link CassAddressInfo }
     *     
     */
    public void setCassAddress(CassAddressInfo value) {
        this.cassAddress = value;
    }

    /**
     * Gets the value of the lastUpdatedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedAddress() {
        return lastUpdatedAddress;
    }

    /**
     * Sets the value of the lastUpdatedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedAddress(XMLGregorianCalendar value) {
        this.lastUpdatedAddress = value;
    }

    /**
     * Gets the value of the rateZoneBanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateZoneBanCode() {
        return rateZoneBanCode;
    }

    /**
     * Sets the value of the rateZoneBanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateZoneBanCode(String value) {
        this.rateZoneBanCode = value;
    }

    /**
     * Gets the value of the geoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoCode() {
        return geoCode;
    }

    /**
     * Sets the value of the geoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoCode(String value) {
        this.geoCode = value;
    }

    /**
     * Gets the value of the addressMatchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressMatchCode() {
        return addressMatchCode;
    }

    /**
     * Sets the value of the addressMatchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressMatchCode(String value) {
        this.addressMatchCode = value;
    }

    /**
     * Gets the value of the disconnectDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisconnectDate() {
        return disconnectDate;
    }

    /**
     * Sets the value of the disconnectDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisconnectDate(XMLGregorianCalendar value) {
        this.disconnectDate = value;
    }

    /**
     * Gets the value of the siteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteId(String value) {
        this.siteId = value;
    }

    /**
     * Gets the value of the siteAddrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteAddrId() {
        return siteAddrId;
    }

    /**
     * Sets the value of the siteAddrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteAddrId(String value) {
        this.siteAddrId = value;
    }

    /**
     * Gets the value of the addressId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * Sets the value of the addressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressId(String value) {
        this.addressId = value;
    }

    /**
     * Gets the value of the legalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntity() {
        return legalEntity;
    }

    /**
     * Sets the value of the legalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntity(String value) {
        this.legalEntity = value;
    }

    /**
     * Gets the value of the buildingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingType() {
        return buildingType;
    }

    /**
     * Sets the value of the buildingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingType(String value) {
        this.buildingType = value;
    }

    /**
     * Gets the value of the tarCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarCode() {
        return tarCode;
    }

    /**
     * Sets the value of the tarCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarCode(String value) {
        this.tarCode = value;
    }

    /**
     * Gets the value of the rateCenterCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCenterCode() {
        return rateCenterCode;
    }

    /**
     * Sets the value of the rateCenterCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCenterCode(String value) {
        this.rateCenterCode = value;
    }

    /**
     * Gets the value of the exchangeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeCode() {
        return exchangeCode;
    }

    /**
     * Sets the value of the exchangeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeCode(String value) {
        this.exchangeCode = value;
    }

    /**
     * Gets the value of the primaryNpaNxx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryNpaNxx() {
        return primaryNpaNxx;
    }

    /**
     * Sets the value of the primaryNpaNxx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryNpaNxx(String value) {
        this.primaryNpaNxx = value;
    }

    /**
     * Gets the value of the clli8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClli8() {
        return clli8;
    }

    /**
     * Sets the value of the clli8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClli8(String value) {
        this.clli8 = value;
    }

    /**
     * Gets the value of the linkKey property.
     * 
     * @return
     *     possible object is
     *     {@link LinkKeyInfo }
     *     
     */
    public LinkKeyInfo getLinkKey() {
        return linkKey;
    }

    /**
     * Sets the value of the linkKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkKeyInfo }
     *     
     */
    public void setLinkKey(LinkKeyInfo value) {
        this.linkKey = value;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the lastDisconnectedTransportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastDisconnectedTransportType() {
        return lastDisconnectedTransportType;
    }

    /**
     * Sets the value of the lastDisconnectedTransportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastDisconnectedTransportType(String value) {
        this.lastDisconnectedTransportType = value;
    }

    /**
     * Gets the value of the lastNADType property.
     * 
     * @return
     *     possible object is
     *     {@link FiberServiceNADTypeInfo }
     *     
     */
    public FiberServiceNADTypeInfo getLastNADType() {
        return lastNADType;
    }

    /**
     * Sets the value of the lastNADType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberServiceNADTypeInfo }
     *     
     */
    public void setLastNADType(FiberServiceNADTypeInfo value) {
        this.lastNADType = value;
    }

    /**
     * Gets the value of the videoHubOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoHubOffice() {
        return videoHubOffice;
    }

    /**
     * Sets the value of the videoHubOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoHubOffice(String value) {
        this.videoHubOffice = value;
    }

    /**
     * Gets the value of the smartMoves property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmartMoves() {
        return smartMoves;
    }

    /**
     * Sets the value of the smartMoves property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmartMoves(String value) {
        this.smartMoves = value;
    }

    /**
     * Gets the value of the exhaustCode property.
     * 
     * @return
     *     possible object is
     *     {@link FiberServiceExhaustCodeInfo }
     *     
     */
    public FiberServiceExhaustCodeInfo getExhaustCode() {
        return exhaustCode;
    }

    /**
     * Sets the value of the exhaustCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberServiceExhaustCodeInfo }
     *     
     */
    public void setExhaustCode(FiberServiceExhaustCodeInfo value) {
        this.exhaustCode = value;
    }

    /**
     * Gets the value of the fttbBuildingClli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFttbBuildingClli() {
        return fttbBuildingClli;
    }

    /**
     * Sets the value of the fttbBuildingClli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFttbBuildingClli(String value) {
        this.fttbBuildingClli = value;
    }

    /**
     * Gets the value of the t1Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isT1Indicator() {
        return t1Indicator;
    }

    /**
     * Sets the value of the t1Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setT1Indicator(Boolean value) {
        this.t1Indicator = value;
    }

    /**
     * Gets the value of the cpeRequiredIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCpeRequiredIndicator() {
        return cpeRequiredIndicator;
    }

    /**
     * Sets the value of the cpeRequiredIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCpeRequiredIndicator(Boolean value) {
        this.cpeRequiredIndicator = value;
    }

    /**
     * Gets the value of the convertedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConvertedIndicator() {
        return convertedIndicator;
    }

    /**
     * Sets the value of the convertedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConvertedIndicator(Boolean value) {
        this.convertedIndicator = value;
    }

    /**
     * Gets the value of the servingAreaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServingAreaDescription() {
        return servingAreaDescription;
    }

    /**
     * Sets the value of the servingAreaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServingAreaDescription(String value) {
        this.servingAreaDescription = value;
    }

    /**
     * Gets the value of the circuitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuitId() {
        return circuitId;
    }

    /**
     * Sets the value of the circuitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuitId(String value) {
        this.circuitId = value;
    }

    /**
     * Gets the value of the fttxConversionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFttxConversionIndicator() {
        return fttxConversionIndicator;
    }

    /**
     * Sets the value of the fttxConversionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFttxConversionIndicator(Boolean value) {
        this.fttxConversionIndicator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressUnrestrictedInfo"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ruralAddressAttention" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressLineInfo" minOccurs="0"/&gt;
     *         &lt;element name="addressSubType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressTypeInfo" minOccurs="0"/&gt;
     *         &lt;element name="internationalAddressLine" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="255"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="internationalZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ruralAddressAttention",
        "addressSubType",
        "internationalAddressLine",
        "internationalZip"
    })
    public static class FieldedAddress
        extends AddressUnrestrictedInfo
    {

        protected String ruralAddressAttention;
        @XmlSchemaType(name = "string")
        protected AddressTypeInfo addressSubType;
        protected String internationalAddressLine;
        protected String internationalZip;

        /**
         * Gets the value of the ruralAddressAttention property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRuralAddressAttention() {
            return ruralAddressAttention;
        }

        /**
         * Sets the value of the ruralAddressAttention property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRuralAddressAttention(String value) {
            this.ruralAddressAttention = value;
        }

        /**
         * Gets the value of the addressSubType property.
         * 
         * @return
         *     possible object is
         *     {@link AddressTypeInfo }
         *     
         */
        public AddressTypeInfo getAddressSubType() {
            return addressSubType;
        }

        /**
         * Sets the value of the addressSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressTypeInfo }
         *     
         */
        public void setAddressSubType(AddressTypeInfo value) {
            this.addressSubType = value;
        }

        /**
         * Gets the value of the internationalAddressLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternationalAddressLine() {
            return internationalAddressLine;
        }

        /**
         * Sets the value of the internationalAddressLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternationalAddressLine(String value) {
            this.internationalAddressLine = value;
        }

        /**
         * Gets the value of the internationalZip property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternationalZip() {
            return internationalZip;
        }

        /**
         * Sets the value of the internationalZip property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternationalZip(String value) {
            this.internationalZip = value;
        }

    }

}
