//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * Detailed FTTB Info. Derives from Base FTTB Info, designed for future expansion.
 * 
 * <p>Java class for FTTBInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FTTBInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="buildingId"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="24"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="customerPremiseLocation" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="9"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fttpProjectCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="7"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="planOfExecutionIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="buildingFiberStatus" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="color" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="6"/&gt;
 *                         &lt;enumeration value="GREEN"/&gt;
 *                         &lt;enumeration value="YELLOW"/&gt;
 *                         &lt;enumeration value="BLUE"/&gt;
 *                         &lt;enumeration value="RED"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="code" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="E"/&gt;
 *                         &lt;enumeration value="F"/&gt;
 *                         &lt;enumeration value="D"/&gt;
 *                         &lt;enumeration value="X"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="yellowDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="insideWireRecommendedCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="buildingCLLI" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI8Info" minOccurs="0"/&gt;
 *         &lt;element name="servingWireCenterCLLI" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI11Info" minOccurs="0"/&gt;
 *         &lt;element name="distributedAntennaSystemIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wifiAvailableIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="smallCellAvailableIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="competitiveTiers" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="emuxEMTLocation" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cableCompetitorName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sharedNTEIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="businessCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="nteFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TrueFalseInfo" minOccurs="0"/&gt;
 *         &lt;element name="nteShareSpareFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TrueFalseInfo" minOccurs="0"/&gt;
 *         &lt;element name="nteNonShareSpareFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TrueFalseInfo" minOccurs="0"/&gt;
 *         &lt;element name="emtFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TrueFalseInfo" minOccurs="0"/&gt;
 *         &lt;element name="emtSpareFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}TrueFalseInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FTTBInfo", propOrder = {
    "buildingId",
    "customerPremiseLocation",
    "fttpProjectCode",
    "planOfExecutionIndicator",
    "buildingFiberStatus",
    "insideWireRecommendedCode",
    "buildingCLLI",
    "servingWireCenterCLLI",
    "distributedAntennaSystemIndicator",
    "wifiAvailableIndicator",
    "smallCellAvailableIndicator",
    "competitiveTiers",
    "emuxEMTLocation",
    "cableCompetitorName",
    "sharedNTEIndicator",
    "businessCount",
    "nteFlag",
    "nteShareSpareFlag",
    "nteNonShareSpareFlag",
    "emtFlag",
    "emtSpareFlag"
})
public class FTTBInfo {

    @XmlElement(required = true)
    protected String buildingId;
    protected String customerPremiseLocation;
    protected String fttpProjectCode;
    protected Boolean planOfExecutionIndicator;
    protected BuildingFiberStatus buildingFiberStatus;
    protected String insideWireRecommendedCode;
    protected String buildingCLLI;
    protected String servingWireCenterCLLI;
    protected String distributedAntennaSystemIndicator;
    protected String wifiAvailableIndicator;
    protected String smallCellAvailableIndicator;
    protected String competitiveTiers;
    protected String emuxEMTLocation;
    protected String cableCompetitorName;
    protected Boolean sharedNTEIndicator;
    protected BigInteger businessCount;
    @XmlSchemaType(name = "string")
    protected TrueFalseInfo nteFlag;
    @XmlSchemaType(name = "string")
    protected TrueFalseInfo nteShareSpareFlag;
    @XmlSchemaType(name = "string")
    protected TrueFalseInfo nteNonShareSpareFlag;
    @XmlSchemaType(name = "string")
    protected TrueFalseInfo emtFlag;
    @XmlSchemaType(name = "string")
    protected TrueFalseInfo emtSpareFlag;

    /**
     * Gets the value of the buildingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * Sets the value of the buildingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingId(String value) {
        this.buildingId = value;
    }

    /**
     * Gets the value of the customerPremiseLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPremiseLocation() {
        return customerPremiseLocation;
    }

    /**
     * Sets the value of the customerPremiseLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPremiseLocation(String value) {
        this.customerPremiseLocation = value;
    }

    /**
     * Gets the value of the fttpProjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFttpProjectCode() {
        return fttpProjectCode;
    }

    /**
     * Sets the value of the fttpProjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFttpProjectCode(String value) {
        this.fttpProjectCode = value;
    }

    /**
     * Gets the value of the planOfExecutionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanOfExecutionIndicator() {
        return planOfExecutionIndicator;
    }

    /**
     * Sets the value of the planOfExecutionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanOfExecutionIndicator(Boolean value) {
        this.planOfExecutionIndicator = value;
    }

    /**
     * Gets the value of the buildingFiberStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingFiberStatus }
     *     
     */
    public BuildingFiberStatus getBuildingFiberStatus() {
        return buildingFiberStatus;
    }

    /**
     * Sets the value of the buildingFiberStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingFiberStatus }
     *     
     */
    public void setBuildingFiberStatus(BuildingFiberStatus value) {
        this.buildingFiberStatus = value;
    }

    /**
     * Gets the value of the insideWireRecommendedCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsideWireRecommendedCode() {
        return insideWireRecommendedCode;
    }

    /**
     * Sets the value of the insideWireRecommendedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsideWireRecommendedCode(String value) {
        this.insideWireRecommendedCode = value;
    }

    /**
     * Gets the value of the buildingCLLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingCLLI() {
        return buildingCLLI;
    }

    /**
     * Sets the value of the buildingCLLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingCLLI(String value) {
        this.buildingCLLI = value;
    }

    /**
     * Gets the value of the servingWireCenterCLLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServingWireCenterCLLI() {
        return servingWireCenterCLLI;
    }

    /**
     * Sets the value of the servingWireCenterCLLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServingWireCenterCLLI(String value) {
        this.servingWireCenterCLLI = value;
    }

    /**
     * Gets the value of the distributedAntennaSystemIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributedAntennaSystemIndicator() {
        return distributedAntennaSystemIndicator;
    }

    /**
     * Sets the value of the distributedAntennaSystemIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributedAntennaSystemIndicator(String value) {
        this.distributedAntennaSystemIndicator = value;
    }

    /**
     * Gets the value of the wifiAvailableIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWifiAvailableIndicator() {
        return wifiAvailableIndicator;
    }

    /**
     * Sets the value of the wifiAvailableIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWifiAvailableIndicator(String value) {
        this.wifiAvailableIndicator = value;
    }

    /**
     * Gets the value of the smallCellAvailableIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmallCellAvailableIndicator() {
        return smallCellAvailableIndicator;
    }

    /**
     * Sets the value of the smallCellAvailableIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmallCellAvailableIndicator(String value) {
        this.smallCellAvailableIndicator = value;
    }

    /**
     * Gets the value of the competitiveTiers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompetitiveTiers() {
        return competitiveTiers;
    }

    /**
     * Sets the value of the competitiveTiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompetitiveTiers(String value) {
        this.competitiveTiers = value;
    }

    /**
     * Gets the value of the emuxEMTLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmuxEMTLocation() {
        return emuxEMTLocation;
    }

    /**
     * Sets the value of the emuxEMTLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmuxEMTLocation(String value) {
        this.emuxEMTLocation = value;
    }

    /**
     * Gets the value of the cableCompetitorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCableCompetitorName() {
        return cableCompetitorName;
    }

    /**
     * Sets the value of the cableCompetitorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCableCompetitorName(String value) {
        this.cableCompetitorName = value;
    }

    /**
     * Gets the value of the sharedNTEIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSharedNTEIndicator() {
        return sharedNTEIndicator;
    }

    /**
     * Sets the value of the sharedNTEIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSharedNTEIndicator(Boolean value) {
        this.sharedNTEIndicator = value;
    }

    /**
     * Gets the value of the businessCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBusinessCount() {
        return businessCount;
    }

    /**
     * Sets the value of the businessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBusinessCount(BigInteger value) {
        this.businessCount = value;
    }

    /**
     * Gets the value of the nteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseInfo }
     *     
     */
    public TrueFalseInfo getNteFlag() {
        return nteFlag;
    }

    /**
     * Sets the value of the nteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseInfo }
     *     
     */
    public void setNteFlag(TrueFalseInfo value) {
        this.nteFlag = value;
    }

    /**
     * Gets the value of the nteShareSpareFlag property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseInfo }
     *     
     */
    public TrueFalseInfo getNteShareSpareFlag() {
        return nteShareSpareFlag;
    }

    /**
     * Sets the value of the nteShareSpareFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseInfo }
     *     
     */
    public void setNteShareSpareFlag(TrueFalseInfo value) {
        this.nteShareSpareFlag = value;
    }

    /**
     * Gets the value of the nteNonShareSpareFlag property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseInfo }
     *     
     */
    public TrueFalseInfo getNteNonShareSpareFlag() {
        return nteNonShareSpareFlag;
    }

    /**
     * Sets the value of the nteNonShareSpareFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseInfo }
     *     
     */
    public void setNteNonShareSpareFlag(TrueFalseInfo value) {
        this.nteNonShareSpareFlag = value;
    }

    /**
     * Gets the value of the emtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseInfo }
     *     
     */
    public TrueFalseInfo getEmtFlag() {
        return emtFlag;
    }

    /**
     * Sets the value of the emtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseInfo }
     *     
     */
    public void setEmtFlag(TrueFalseInfo value) {
        this.emtFlag = value;
    }

    /**
     * Gets the value of the emtSpareFlag property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseInfo }
     *     
     */
    public TrueFalseInfo getEmtSpareFlag() {
        return emtSpareFlag;
    }

    /**
     * Sets the value of the emtSpareFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseInfo }
     *     
     */
    public void setEmtSpareFlag(TrueFalseInfo value) {
        this.emtSpareFlag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="color" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="6"/&gt;
     *               &lt;enumeration value="GREEN"/&gt;
     *               &lt;enumeration value="YELLOW"/&gt;
     *               &lt;enumeration value="BLUE"/&gt;
     *               &lt;enumeration value="RED"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="code" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="E"/&gt;
     *               &lt;enumeration value="F"/&gt;
     *               &lt;enumeration value="D"/&gt;
     *               &lt;enumeration value="X"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="yellowDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "color",
        "code",
        "yellowDate"
    })
    public static class BuildingFiberStatus {

        protected String color;
        protected String code;
        protected String yellowDate;

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the yellowDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getYellowDate() {
            return yellowDate;
        }

        /**
         * Sets the value of the yellowDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYellowDate(String value) {
            this.yellowDate = value;
        }

    }

}
