//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkKeyInfo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LinkKeyInfo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;length value="1"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="U"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LinkKeyInfo")
@XmlEnum
public enum LinkKeyInfo {

    M,
    U,
    D,
    B,
    F,
    E,
    P,
    G,
    L,
    H,
    I,
    C,
    A,
    S;

    public String value() {
        return name();
    }

    public static LinkKeyInfo fromValue(String v) {
        return valueOf(v);
    }

}
