//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for NetworkTransportDetailsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkTransportDetailsInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="UnnormalizedTotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="networkTransportType" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceNetworkTypeInfo"/&gt;
 *         &lt;element name="networkPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="exhaustCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceExhaustCodeInfo" minOccurs="0"/&gt;
 *         &lt;element name="bondedPairCapable" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="bondedPairExists" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="activatedDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
 *         &lt;element name="isTransportTypeActive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="networkGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="preferredNetworkIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="HighestHSIASpeed" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}HighestHSIASpeedInfo" minOccurs="0"/&gt;
 *         &lt;element name="servingAreaDescription" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SubTransport" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="frequency17MhzIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="vectoringIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="t1Indicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="exhaustCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceExhaustCodeInfo" minOccurs="0"/&gt;
 *                   &lt;element name="billingAccountNumber" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BillingAccountNumberInfo" minOccurs="0"/&gt;
 *                   &lt;element name="networkAccessDeviceType" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="0"/&gt;
 *                         &lt;maxLength value="4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="disconnectDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
 *                   &lt;element name="activatedDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
 *                   &lt;element name="TotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="UnnormalizedTotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="HighestHSIASpeed" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}HighestHSIASpeedInfo" minOccurs="0"/&gt;
 *                   &lt;element name="Products" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceProductQualificationInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="abfGPONCapacityIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="abfGPONEstimatedCompletionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkTransportDetailsInfo", propOrder = {
    "totalBandwidth",
    "unnormalizedTotalBandwidth",
    "networkTransportType",
    "networkPriority",
    "exhaustCode",
    "bondedPairCapable",
    "bondedPairExists",
    "activatedDate",
    "isTransportTypeActive",
    "networkGroup",
    "preferredNetworkIndicator",
    "highestHSIASpeed",
    "servingAreaDescription",
    "subTransport",
    "abfGPONCapacityIndicator",
    "abfGPONEstimatedCompletionDate"
})
public class NetworkTransportDetailsInfo {

    @XmlElement(name = "TotalBandwidth")
    protected List<NetworkTransportBandwidthInfo> totalBandwidth;
    @XmlElement(name = "UnnormalizedTotalBandwidth")
    protected List<NetworkTransportBandwidthInfo> unnormalizedTotalBandwidth;
    @XmlElement(required = true)
    protected String networkTransportType;
    protected String networkPriority;
    @XmlSchemaType(name = "string")
    protected FiberServiceExhaustCodeInfo exhaustCode;
    protected String bondedPairCapable;
    protected Boolean bondedPairExists;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar activatedDate;
    protected Boolean isTransportTypeActive;
    protected String networkGroup;
    protected Boolean preferredNetworkIndicator;
    @XmlElement(name = "HighestHSIASpeed")
    protected HighestHSIASpeedInfo highestHSIASpeed;
    protected String servingAreaDescription;
    @XmlElement(name = "SubTransport")
    protected List<SubTransport> subTransport;
    protected Boolean abfGPONCapacityIndicator;
    protected String abfGPONEstimatedCompletionDate;

    /**
     * Gets the value of the totalBandwidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalBandwidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalBandwidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkTransportBandwidthInfo }
     * 
     * 
     */
    public List<NetworkTransportBandwidthInfo> getTotalBandwidth() {
        if (totalBandwidth == null) {
            totalBandwidth = new ArrayList<NetworkTransportBandwidthInfo>();
        }
        return this.totalBandwidth;
    }

    /**
     * Gets the value of the unnormalizedTotalBandwidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unnormalizedTotalBandwidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnnormalizedTotalBandwidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkTransportBandwidthInfo }
     * 
     * 
     */
    public List<NetworkTransportBandwidthInfo> getUnnormalizedTotalBandwidth() {
        if (unnormalizedTotalBandwidth == null) {
            unnormalizedTotalBandwidth = new ArrayList<NetworkTransportBandwidthInfo>();
        }
        return this.unnormalizedTotalBandwidth;
    }

    /**
     * Gets the value of the networkTransportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkTransportType() {
        return networkTransportType;
    }

    /**
     * Sets the value of the networkTransportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkTransportType(String value) {
        this.networkTransportType = value;
    }

    /**
     * Gets the value of the networkPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkPriority() {
        return networkPriority;
    }

    /**
     * Sets the value of the networkPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkPriority(String value) {
        this.networkPriority = value;
    }

    /**
     * Gets the value of the exhaustCode property.
     * 
     * @return
     *     possible object is
     *     {@link FiberServiceExhaustCodeInfo }
     *     
     */
    public FiberServiceExhaustCodeInfo getExhaustCode() {
        return exhaustCode;
    }

    /**
     * Sets the value of the exhaustCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberServiceExhaustCodeInfo }
     *     
     */
    public void setExhaustCode(FiberServiceExhaustCodeInfo value) {
        this.exhaustCode = value;
    }

    /**
     * Gets the value of the bondedPairCapable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondedPairCapable() {
        return bondedPairCapable;
    }

    /**
     * Sets the value of the bondedPairCapable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondedPairCapable(String value) {
        this.bondedPairCapable = value;
    }

    /**
     * Gets the value of the bondedPairExists property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBondedPairExists() {
        return bondedPairExists;
    }

    /**
     * Sets the value of the bondedPairExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBondedPairExists(Boolean value) {
        this.bondedPairExists = value;
    }

    /**
     * Gets the value of the activatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivatedDate() {
        return activatedDate;
    }

    /**
     * Sets the value of the activatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivatedDate(XMLGregorianCalendar value) {
        this.activatedDate = value;
    }

    /**
     * Gets the value of the isTransportTypeActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTransportTypeActive() {
        return isTransportTypeActive;
    }

    /**
     * Sets the value of the isTransportTypeActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTransportTypeActive(Boolean value) {
        this.isTransportTypeActive = value;
    }

    /**
     * Gets the value of the networkGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkGroup() {
        return networkGroup;
    }

    /**
     * Sets the value of the networkGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkGroup(String value) {
        this.networkGroup = value;
    }

    /**
     * Gets the value of the preferredNetworkIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreferredNetworkIndicator() {
        return preferredNetworkIndicator;
    }

    /**
     * Sets the value of the preferredNetworkIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreferredNetworkIndicator(Boolean value) {
        this.preferredNetworkIndicator = value;
    }

    /**
     * Gets the value of the highestHSIASpeed property.
     * 
     * @return
     *     possible object is
     *     {@link HighestHSIASpeedInfo }
     *     
     */
    public HighestHSIASpeedInfo getHighestHSIASpeed() {
        return highestHSIASpeed;
    }

    /**
     * Sets the value of the highestHSIASpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighestHSIASpeedInfo }
     *     
     */
    public void setHighestHSIASpeed(HighestHSIASpeedInfo value) {
        this.highestHSIASpeed = value;
    }

    /**
     * Gets the value of the servingAreaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServingAreaDescription() {
        return servingAreaDescription;
    }

    /**
     * Sets the value of the servingAreaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServingAreaDescription(String value) {
        this.servingAreaDescription = value;
    }

    /**
     * Gets the value of the subTransport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subTransport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubTransport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubTransport }
     * 
     * 
     */
    public List<SubTransport> getSubTransport() {
        if (subTransport == null) {
            subTransport = new ArrayList<SubTransport>();
        }
        return this.subTransport;
    }

    /**
     * Gets the value of the abfGPONCapacityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbfGPONCapacityIndicator() {
        return abfGPONCapacityIndicator;
    }

    /**
     * Sets the value of the abfGPONCapacityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbfGPONCapacityIndicator(Boolean value) {
        this.abfGPONCapacityIndicator = value;
    }

    /**
     * Gets the value of the abfGPONEstimatedCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbfGPONEstimatedCompletionDate() {
        return abfGPONEstimatedCompletionDate;
    }

    /**
     * Sets the value of the abfGPONEstimatedCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbfGPONEstimatedCompletionDate(String value) {
        this.abfGPONEstimatedCompletionDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="frequency17MhzIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="vectoringIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="t1Indicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="exhaustCode" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceExhaustCodeInfo" minOccurs="0"/&gt;
     *         &lt;element name="billingAccountNumber" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BillingAccountNumberInfo" minOccurs="0"/&gt;
     *         &lt;element name="networkAccessDeviceType" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="0"/&gt;
     *               &lt;maxLength value="4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="disconnectDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
     *         &lt;element name="activatedDate" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}DateWithTimezoneInfo" minOccurs="0"/&gt;
     *         &lt;element name="TotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="UnnormalizedTotalBandwidth" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}NetworkTransportBandwidthInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="HighestHSIASpeed" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}HighestHSIASpeedInfo" minOccurs="0"/&gt;
     *         &lt;element name="Products" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}FiberServiceProductQualificationInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "frequency17MhzIndicator",
        "vectoringIndicator",
        "t1Indicator",
        "exhaustCode",
        "billingAccountNumber",
        "networkAccessDeviceType",
        "disconnectDate",
        "activatedDate",
        "totalBandwidth",
        "unnormalizedTotalBandwidth",
        "highestHSIASpeed",
        "products"
    })
    public static class SubTransport {

        protected Boolean frequency17MhzIndicator;
        protected Boolean vectoringIndicator;
        protected Boolean t1Indicator;
        @XmlSchemaType(name = "string")
        protected FiberServiceExhaustCodeInfo exhaustCode;
        protected String billingAccountNumber;
        protected String networkAccessDeviceType;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar disconnectDate;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar activatedDate;
        @XmlElement(name = "TotalBandwidth")
        protected List<NetworkTransportBandwidthInfo> totalBandwidth;
        @XmlElement(name = "UnnormalizedTotalBandwidth")
        protected List<NetworkTransportBandwidthInfo> unnormalizedTotalBandwidth;
        @XmlElement(name = "HighestHSIASpeed")
        protected HighestHSIASpeedInfo highestHSIASpeed;
        @XmlElement(name = "Products")
        protected List<FiberServiceProductQualificationInfo> products;

        /**
         * Gets the value of the frequency17MhzIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFrequency17MhzIndicator() {
            return frequency17MhzIndicator;
        }

        /**
         * Sets the value of the frequency17MhzIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFrequency17MhzIndicator(Boolean value) {
            this.frequency17MhzIndicator = value;
        }

        /**
         * Gets the value of the vectoringIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isVectoringIndicator() {
            return vectoringIndicator;
        }

        /**
         * Sets the value of the vectoringIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setVectoringIndicator(Boolean value) {
            this.vectoringIndicator = value;
        }

        /**
         * Gets the value of the t1Indicator property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isT1Indicator() {
            return t1Indicator;
        }

        /**
         * Sets the value of the t1Indicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setT1Indicator(Boolean value) {
            this.t1Indicator = value;
        }

        /**
         * Gets the value of the exhaustCode property.
         * 
         * @return
         *     possible object is
         *     {@link FiberServiceExhaustCodeInfo }
         *     
         */
        public FiberServiceExhaustCodeInfo getExhaustCode() {
            return exhaustCode;
        }

        /**
         * Sets the value of the exhaustCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link FiberServiceExhaustCodeInfo }
         *     
         */
        public void setExhaustCode(FiberServiceExhaustCodeInfo value) {
            this.exhaustCode = value;
        }

        /**
         * Gets the value of the billingAccountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingAccountNumber() {
            return billingAccountNumber;
        }

        /**
         * Sets the value of the billingAccountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingAccountNumber(String value) {
            this.billingAccountNumber = value;
        }

        /**
         * Gets the value of the networkAccessDeviceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkAccessDeviceType() {
            return networkAccessDeviceType;
        }

        /**
         * Sets the value of the networkAccessDeviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkAccessDeviceType(String value) {
            this.networkAccessDeviceType = value;
        }

        /**
         * Gets the value of the disconnectDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDisconnectDate() {
            return disconnectDate;
        }

        /**
         * Sets the value of the disconnectDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDisconnectDate(XMLGregorianCalendar value) {
            this.disconnectDate = value;
        }

        /**
         * Gets the value of the activatedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getActivatedDate() {
            return activatedDate;
        }

        /**
         * Sets the value of the activatedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setActivatedDate(XMLGregorianCalendar value) {
            this.activatedDate = value;
        }

        /**
         * Gets the value of the totalBandwidth property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the totalBandwidth property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTotalBandwidth().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NetworkTransportBandwidthInfo }
         * 
         * 
         */
        public List<NetworkTransportBandwidthInfo> getTotalBandwidth() {
            if (totalBandwidth == null) {
                totalBandwidth = new ArrayList<NetworkTransportBandwidthInfo>();
            }
            return this.totalBandwidth;
        }

        /**
         * Gets the value of the unnormalizedTotalBandwidth property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unnormalizedTotalBandwidth property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnnormalizedTotalBandwidth().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NetworkTransportBandwidthInfo }
         * 
         * 
         */
        public List<NetworkTransportBandwidthInfo> getUnnormalizedTotalBandwidth() {
            if (unnormalizedTotalBandwidth == null) {
                unnormalizedTotalBandwidth = new ArrayList<NetworkTransportBandwidthInfo>();
            }
            return this.unnormalizedTotalBandwidth;
        }

        /**
         * Gets the value of the highestHSIASpeed property.
         * 
         * @return
         *     possible object is
         *     {@link HighestHSIASpeedInfo }
         *     
         */
        public HighestHSIASpeedInfo getHighestHSIASpeed() {
            return highestHSIASpeed;
        }

        /**
         * Sets the value of the highestHSIASpeed property.
         * 
         * @param value
         *     allowed object is
         *     {@link HighestHSIASpeedInfo }
         *     
         */
        public void setHighestHSIASpeed(HighestHSIASpeedInfo value) {
            this.highestHSIASpeed = value;
        }

        /**
         * Gets the value of the products property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the products property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProducts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FiberServiceProductQualificationInfo }
         * 
         * 
         */
        public List<FiberServiceProductQualificationInfo> getProducts() {
            if (products == null) {
                products = new ArrayList<FiberServiceProductQualificationInfo>();
            }
            return this.products;
        }

    }

}
