//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTypeInfo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceTypeInfo"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UMC"/&gt;
 *     &lt;enumeration value="VOIPLN"/&gt;
 *     &lt;enumeration value="CVOIP"/&gt;
 *     &lt;enumeration value="WS"/&gt;
 *     &lt;enumeration value="WSBAN"/&gt;
 *     &lt;enumeration value="PLS"/&gt;
 *     &lt;enumeration value="ALL"/&gt;
 *     &lt;enumeration value="RG"/&gt;
 *     &lt;enumeration value="VBP"/&gt;
 *     &lt;enumeration value="STB"/&gt;
 *     &lt;enumeration value="QUEST"/&gt;
 *     &lt;enumeration value="BVOIP"/&gt;
 *     &lt;enumeration value="MIS"/&gt;
 *     &lt;enumeration value="AVPN"/&gt;
 *     &lt;enumeration value="CLOUD"/&gt;
 *     &lt;enumeration value="OEW"/&gt;
 *     &lt;enumeration value="EPLS-WAN"/&gt;
 *     &lt;enumeration value="PNT"/&gt;
 *     &lt;enumeration value="EPLS"/&gt;
 *     &lt;enumeration value="AVPN-ETH"/&gt;
 *     &lt;enumeration value="OPT-E-WAN"/&gt;
 *     &lt;enumeration value="EVPN"/&gt;
 *     &lt;enumeration value="MRS"/&gt;
 *     &lt;enumeration value="OUTSOURCING"/&gt;
 *     &lt;enumeration value="GMIS"/&gt;
 *     &lt;enumeration value="IP_TELEPHONY"/&gt;
 *     &lt;enumeration value="MLAN"/&gt;
 *     &lt;enumeration value="MSS"/&gt;
 *     &lt;enumeration value="VOICE"/&gt;
 *     &lt;enumeration value="AVTS"/&gt;
 *     &lt;enumeration value="GENERIC_SERVICE"/&gt;
 *     &lt;enumeration value="ASE"/&gt;
 *     &lt;enumeration value="IPFR"/&gt;
 *     &lt;enumeration value="FR"/&gt;
 *     &lt;enumeration value="ATM"/&gt;
 *     &lt;enumeration value="ATS"/&gt;
 *     &lt;enumeration value="MOBILITY"/&gt;
 *     &lt;enumeration value="CAAS"/&gt;
 *     &lt;enumeration value="PASS"/&gt;
 *     &lt;enumeration value="STAAS"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="NODAL"/&gt;
 *     &lt;enumeration value="NB_IPVPN"/&gt;
 *     &lt;enumeration value="EAPI"/&gt;
 *     &lt;enumeration value="ANIRA"/&gt;
 *     &lt;enumeration value="SDN-MIS"/&gt;
 *     &lt;enumeration value="SDN-ETHERNET"/&gt;
 *     &lt;enumeration value="HOSTED_COMMUNICATIONS"/&gt;
 *     &lt;enumeration value="HSIA-E"/&gt;
 *     &lt;enumeration value="uCPE-VMS"/&gt;
 *     &lt;enumeration value="EMMS"/&gt;
 *     &lt;enumeration value="ASEOD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceTypeInfo")
@XmlEnum
public enum ServiceTypeInfo {

    UMC("UMC"),
    VOIPLN("VOIPLN"),
    CVOIP("CVOIP"),
    WS("WS"),
    WSBAN("WSBAN"),
    PLS("PLS"),
    ALL("ALL"),
    RG("RG"),
    VBP("VBP"),
    STB("STB"),
    QUEST("QUEST"),
    BVOIP("BVOIP"),
    MIS("MIS"),
    AVPN("AVPN"),
    CLOUD("CLOUD"),
    OEW("OEW"),
    @XmlEnumValue("EPLS-WAN")
    EPLS_WAN("EPLS-WAN"),
    PNT("PNT"),
    EPLS("EPLS"),
    @XmlEnumValue("AVPN-ETH")
    AVPN_ETH("AVPN-ETH"),
    @XmlEnumValue("OPT-E-WAN")
    OPT_E_WAN("OPT-E-WAN"),
    EVPN("EVPN"),
    MRS("MRS"),
    OUTSOURCING("OUTSOURCING"),
    GMIS("GMIS"),
    IP_TELEPHONY("IP_TELEPHONY"),
    MLAN("MLAN"),
    MSS("MSS"),
    VOICE("VOICE"),
    AVTS("AVTS"),
    GENERIC_SERVICE("GENERIC_SERVICE"),
    ASE("ASE"),
    IPFR("IPFR"),
    FR("FR"),
    ATM("ATM"),
    ATS("ATS"),
    MOBILITY("MOBILITY"),
    CAAS("CAAS"),
    PASS("PASS"),
    STAAS("STAAS"),
    PL("PL"),
    NODAL("NODAL"),
    NB_IPVPN("NB_IPVPN"),
    EAPI("EAPI"),
    ANIRA("ANIRA"),
    @XmlEnumValue("SDN-MIS")
    SDN_MIS("SDN-MIS"),
    @XmlEnumValue("SDN-ETHERNET")
    SDN_ETHERNET("SDN-ETHERNET"),
    HOSTED_COMMUNICATIONS("HOSTED_COMMUNICATIONS"),
    @XmlEnumValue("HSIA-E")
    HSIA_E("HSIA-E"),
    @XmlEnumValue("uCPE-VMS")
    U_CPE_VMS("uCPE-VMS"),
    EMMS("EMMS"),
    ASEOD("ASEOD");
    private final String value;

    ServiceTypeInfo(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTypeInfo fromValue(String v) {
        for (ServiceTypeInfo c: ServiceTypeInfo.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
