//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SoftwareDefinedNetworkingInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareDefinedNetworkingInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sdnIndicator" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="emtCLLI11" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI11Info"&gt;
 *               &lt;maxLength value="11"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="multiDemarkType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="outdoorEMTFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanStringInfo" minOccurs="0"/&gt;
 *         &lt;element name="tier" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lataCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lataName" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="standardAddress" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="250"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="regionCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="O"/&gt;
 *               &lt;enumeration value="Y"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="attAffiliate" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ipagFlag" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}BooleanTrueInfo" minOccurs="0"/&gt;
 *         &lt;element name="latitude" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}LatitudeInfo" minOccurs="0"/&gt;
 *         &lt;element name="longitude" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}LongitudeInfo" minOccurs="0"/&gt;
 *         &lt;element name="AICNodes" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="attIntegratedCloudNodeCLLI" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI11Info" minOccurs="0"/&gt;
 *                   &lt;element name="attIntegratedCloudNodeState" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressStateInfo" minOccurs="0"/&gt;
 *                   &lt;element name="attIntegratedCloudNodeCity" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressCityInfo" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PortBandwidth" maxOccurs="10" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="interfaceType" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="OPTICAL"/&gt;
 *                         &lt;enumeration value="ELECTRICAL"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="uniCIR" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                         &lt;minInclusive value="2"/&gt;
 *                         &lt;maxInclusive value="100000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareDefinedNetworkingInfo", propOrder = {
    "sdnIndicator",
    "emtCLLI11",
    "multiDemarkType",
    "outdoorEMTFlag",
    "tier",
    "lataCode",
    "lataName",
    "standardAddress",
    "regionCode",
    "attAffiliate",
    "ipagFlag",
    "latitude",
    "longitude",
    "aicNodes",
    "portBandwidth"
})
public class SoftwareDefinedNetworkingInfo {

    protected Boolean sdnIndicator;
    protected String emtCLLI11;
    protected String multiDemarkType;
    @XmlSchemaType(name = "string")
    protected BooleanStringInfo outdoorEMTFlag;
    protected String tier;
    protected String lataCode;
    protected String lataName;
    protected String standardAddress;
    protected String regionCode;
    protected String attAffiliate;
    protected Boolean ipagFlag;
    protected Double latitude;
    protected Double longitude;
    @XmlElement(name = "AICNodes")
    protected List<AICNodes> aicNodes;
    @XmlElement(name = "PortBandwidth")
    protected List<PortBandwidth> portBandwidth;

    /**
     * Gets the value of the sdnIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSdnIndicator() {
        return sdnIndicator;
    }

    /**
     * Sets the value of the sdnIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSdnIndicator(Boolean value) {
        this.sdnIndicator = value;
    }

    /**
     * Gets the value of the emtCLLI11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmtCLLI11() {
        return emtCLLI11;
    }

    /**
     * Sets the value of the emtCLLI11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmtCLLI11(String value) {
        this.emtCLLI11 = value;
    }

    /**
     * Gets the value of the multiDemarkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiDemarkType() {
        return multiDemarkType;
    }

    /**
     * Sets the value of the multiDemarkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiDemarkType(String value) {
        this.multiDemarkType = value;
    }

    /**
     * Gets the value of the outdoorEMTFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanStringInfo }
     *     
     */
    public BooleanStringInfo getOutdoorEMTFlag() {
        return outdoorEMTFlag;
    }

    /**
     * Sets the value of the outdoorEMTFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanStringInfo }
     *     
     */
    public void setOutdoorEMTFlag(BooleanStringInfo value) {
        this.outdoorEMTFlag = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier(String value) {
        this.tier = value;
    }

    /**
     * Gets the value of the lataCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLataCode() {
        return lataCode;
    }

    /**
     * Sets the value of the lataCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLataCode(String value) {
        this.lataCode = value;
    }

    /**
     * Gets the value of the lataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLataName() {
        return lataName;
    }

    /**
     * Sets the value of the lataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLataName(String value) {
        this.lataName = value;
    }

    /**
     * Gets the value of the standardAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardAddress() {
        return standardAddress;
    }

    /**
     * Sets the value of the standardAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardAddress(String value) {
        this.standardAddress = value;
    }

    /**
     * Gets the value of the regionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the attAffiliate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttAffiliate() {
        return attAffiliate;
    }

    /**
     * Sets the value of the attAffiliate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttAffiliate(String value) {
        this.attAffiliate = value;
    }

    /**
     * Gets the value of the ipagFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIpagFlag() {
        return ipagFlag;
    }

    /**
     * Sets the value of the ipagFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIpagFlag(Boolean value) {
        this.ipagFlag = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLatitude(Double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLongitude(Double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the aicNodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aicNodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAICNodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AICNodes }
     * 
     * 
     */
    public List<AICNodes> getAICNodes() {
        if (aicNodes == null) {
            aicNodes = new ArrayList<AICNodes>();
        }
        return this.aicNodes;
    }

    /**
     * Gets the value of the portBandwidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portBandwidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortBandwidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortBandwidth }
     * 
     * 
     */
    public List<PortBandwidth> getPortBandwidth() {
        if (portBandwidth == null) {
            portBandwidth = new ArrayList<PortBandwidth>();
        }
        return this.portBandwidth;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="attIntegratedCloudNodeCLLI" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}CLLI11Info" minOccurs="0"/&gt;
     *         &lt;element name="attIntegratedCloudNodeState" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressStateInfo" minOccurs="0"/&gt;
     *         &lt;element name="attIntegratedCloudNodeCity" type="{http://csi.att.com/CSI/Namespaces/OVALSGISAddressValidationServiceQualUB/Types/Public/CommonDataModel.xsd}AddressCityInfo" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attIntegratedCloudNodeCLLI",
        "attIntegratedCloudNodeState",
        "attIntegratedCloudNodeCity"
    })
    public static class AICNodes {

        protected String attIntegratedCloudNodeCLLI;
        @XmlSchemaType(name = "string")
        protected AddressStateInfo attIntegratedCloudNodeState;
        protected String attIntegratedCloudNodeCity;

        /**
         * Gets the value of the attIntegratedCloudNodeCLLI property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttIntegratedCloudNodeCLLI() {
            return attIntegratedCloudNodeCLLI;
        }

        /**
         * Sets the value of the attIntegratedCloudNodeCLLI property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttIntegratedCloudNodeCLLI(String value) {
            this.attIntegratedCloudNodeCLLI = value;
        }

        /**
         * Gets the value of the attIntegratedCloudNodeState property.
         * 
         * @return
         *     possible object is
         *     {@link AddressStateInfo }
         *     
         */
        public AddressStateInfo getAttIntegratedCloudNodeState() {
            return attIntegratedCloudNodeState;
        }

        /**
         * Sets the value of the attIntegratedCloudNodeState property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressStateInfo }
         *     
         */
        public void setAttIntegratedCloudNodeState(AddressStateInfo value) {
            this.attIntegratedCloudNodeState = value;
        }

        /**
         * Gets the value of the attIntegratedCloudNodeCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttIntegratedCloudNodeCity() {
            return attIntegratedCloudNodeCity;
        }

        /**
         * Sets the value of the attIntegratedCloudNodeCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttIntegratedCloudNodeCity(String value) {
            this.attIntegratedCloudNodeCity = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="interfaceType" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="OPTICAL"/&gt;
     *               &lt;enumeration value="ELECTRICAL"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="uniCIR" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *               &lt;minInclusive value="2"/&gt;
     *               &lt;maxInclusive value="100000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interfaceType",
        "uniCIR"
    })
    public static class PortBandwidth {

        protected String interfaceType;
        protected Integer uniCIR;

        /**
         * Gets the value of the interfaceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterfaceType() {
            return interfaceType;
        }

        /**
         * Sets the value of the interfaceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterfaceType(String value) {
            this.interfaceType = value;
        }

        /**
         * Gets the value of the uniCIR property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUniCIR() {
            return uniCIR;
        }

        /**
         * Sets the value of the uniCIR property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUniCIR(Integer value) {
            this.uniCIR = value;
        }

    }

}
