package com.sbc.gwsvcs.service.facsaccess.interfaces;


final public class EPLUAF_Section_t implements org.omg.CORBA.portable.IDLEntity { 
	public String PRT;
	public String STEP;
	public String BLTYPE;
	public String DREC;
	public String NO;
	public String ST;
	public String UNTYP;
	public String UNIT;
	public String ELEVTYP;
	public String FLR;
	public String STRUCTYP;
	public String BLDG;
	public String NEWSTR;
	public String COM;
	public String STATE;
	public String MKSEG;
	public String ACCT;
	public String CSW;
	public String STEA;
	public String LRST;
	public String LRMK;
	public String CID;
	public String CKT2;
	public String CLCI;
	public String CKT3;
	public String USOC;
	public String MUR;
	public String AFSTAT;
	public String DATE;
	public String ADL;
	public String SSP;
	public String SSM;
	public String ESL;
	public String ADSR;
	public String SUBL;
	public String SUS;
	public String TSP;
	public String BDG;
	public String SSC;
	public String RTF;
	public String OWS;
	public String WOL;
	public String DTEA;
	public String CSWEX;
	public String TRM;
	public String WW;
	public String POS;
	public String JACK;
	public String BP;
	public com.sbc.gwsvcs.service.facsaccess.interfaces.LSEG_t[] LSEG;
	public com.sbc.gwsvcs.service.facsaccess.interfaces.EPOEC_t[] EPOEC;
	public com.sbc.gwsvcs.service.facsaccess.interfaces.EAPNT_t[] EAPNT;

	public EPLUAF_Section_t () {
	}
	public EPLUAF_Section_t (String PRT, String STEP, String BLTYPE, String DREC, String NO, String ST, String UNTYP, String UNIT, String ELEVTYP, String FLR, String STRUCTYP, String BLDG, String NEWSTR, String COM, String STATE, String MKSEG, String ACCT, String CSW, String STEA, String LRST, String LRMK, String CID, String CKT2, String CLCI, String CKT3, String USOC, String MUR, String AFSTAT, String DATE, String ADL, String SSP, String SSM, String ESL, String ADSR, String SUBL, String SUS, String TSP, String BDG, String SSC, String RTF, String OWS, String WOL, String DTEA, String CSWEX, String TRM, String WW, String POS, String JACK, String BP, com.sbc.gwsvcs.service.facsaccess.interfaces.LSEG_t[] LSEG, com.sbc.gwsvcs.service.facsaccess.interfaces.EPOEC_t[] EPOEC, com.sbc.gwsvcs.service.facsaccess.interfaces.EAPNT_t[] EAPNT) { 
		this.PRT = PRT;
		this.STEP = STEP;
		this.BLTYPE = BLTYPE;
		this.DREC = DREC;
		this.NO = NO;
		this.ST = ST;
		this.UNTYP = UNTYP;
		this.UNIT = UNIT;
		this.ELEVTYP = ELEVTYP;
		this.FLR = FLR;
		this.STRUCTYP = STRUCTYP;
		this.BLDG = BLDG;
		this.NEWSTR = NEWSTR;
		this.COM = COM;
		this.STATE = STATE;
		this.MKSEG = MKSEG;
		this.ACCT = ACCT;
		this.CSW = CSW;
		this.STEA = STEA;
		this.LRST = LRST;
		this.LRMK = LRMK;
		this.CID = CID;
		this.CKT2 = CKT2;
		this.CLCI = CLCI;
		this.CKT3 = CKT3;
		this.USOC = USOC;
		this.MUR = MUR;
		this.AFSTAT = AFSTAT;
		this.DATE = DATE;
		this.ADL = ADL;
		this.SSP = SSP;
		this.SSM = SSM;
		this.ESL = ESL;
		this.ADSR = ADSR;
		this.SUBL = SUBL;
		this.SUS = SUS;
		this.TSP = TSP;
		this.BDG = BDG;
		this.SSC = SSC;
		this.RTF = RTF;
		this.OWS = OWS;
		this.WOL = WOL;
		this.DTEA = DTEA;
		this.CSWEX = CSWEX;
		this.TRM = TRM;
		this.WW = WW;
		this.POS = POS;
		this.JACK = JACK;
		this.BP = BP;
		this.LSEG = LSEG;
		this.EPOEC = EPOEC;
		this.EAPNT = EAPNT;

	} 
}
