//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.06 at 02:20:41 PM PST 
//


package com.att.lms.bis.service.ovals.model.pavs.response1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for postalAddressValidationServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="postalAddressValidationServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="USPSDeliveryPointValidationAttributes" type="{http://ovalgis.att.com/PostalAddressValidationResponse.xsd}USPSDeliveryPointValidationAttributesType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="HostResponse" type="{http://ovalgis.att.com/PostalAddressValidationResponse.xsd}HostResponseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "postalAddressValidationServiceResponseType", namespace = "http://ovalgis.att.com/PostalAddressValidationResponse.xsd", propOrder = {
    "uspsDeliveryPointValidationAttributes",
    "hostResponse"
})
@XmlSeeAlso({
    PostalAddressValidationServiceResponse.class
})
public class PostalAddressValidationServiceResponseType {

    @XmlElement(name = "USPSDeliveryPointValidationAttributes")
    protected List<USPSDeliveryPointValidationAttributesType> uspsDeliveryPointValidationAttributes;
    @XmlElement(name = "HostResponse", required = true)
    protected HostResponseType hostResponse;

    /**
     * Gets the value of the uspsDeliveryPointValidationAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uspsDeliveryPointValidationAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUSPSDeliveryPointValidationAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link USPSDeliveryPointValidationAttributesType }
     * 
     * 
     */
    public List<USPSDeliveryPointValidationAttributesType> getUSPSDeliveryPointValidationAttributes() {
        if (uspsDeliveryPointValidationAttributes == null) {
            uspsDeliveryPointValidationAttributes = new ArrayList<USPSDeliveryPointValidationAttributesType>();
        }
        return this.uspsDeliveryPointValidationAttributes;
    }

    /**
     * Gets the value of the hostResponse property.
     * 
     * @return
     *     possible object is
     *     {@link HostResponseType }
     *     
     */
    public HostResponseType getHostResponse() {
        return hostResponse;
    }

    /**
     * Sets the value of the hostResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostResponseType }
     *     
     */
    public void setHostResponse(HostResponseType value) {
        this.hostResponse = value;
    }

}
