//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://csi.cingular.com/CSI/Namespaces/Container/Public/AddressValidationServiceQualificationUnifiedBillRequest.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.att.lms.bis.service.ovals.model.avsqub.request;
