// $Id: ASONSagValidResp.java,v 1.1 2002/09/29 03:53:47 dm2328 Exp $

package com.sbc.gwsvcs.service.asonservice.interfaces;

import com.sbc.vicunalite.api.*;

final public class ASONSagValidResp implements java.io.Serializable { 
	public com.sbc.gwsvcs.service.asonservice.interfaces.comReplyHdr1_st comReplyHdr1;
	public com.sbc.gwsvcs.service.asonservice.interfaces.comReplyHdr2_st comReplyHdr2;
	public String raiCode;
	public char sagAreaId;
	public char alphaNumInd;
	public String addressNameSag;
	public String directional;
	public String highAddrRange;
	public String lowAddrRange;
	public char oddEvenIndicator;
	public String exchange;
	public String centralOffice;
	public String map;
	public char rateBand;
	public char rateZone;
	public String zipCodeSag;
	public String npa;
	public String countyAbbrev;
	public String municipality;
	public String sagWireCenter;
	public String communitySag;
	public String state;
	public char needBillAddrInd;
	public char editAgainstLufFile;
	public char needLocLevel1Ind;
	public char needLocLevel2Ind;
	public char needLocLevel3Ind;
	public char needCommNameInd;
	public char secondLineInd;
	public char metroOptSvcInd;
	public char omitCentralOfficeInd;
	public char remarksInd;
	public String lastAssignedHouseNumUsed;
	public String cityAbbreviation;
	public char populateCommNameInd;
	public char alternateAddressInd;
	public char lfacsDupAddressInd;
	public String equipmentType;
	public char analogOrDigitalType;
	public String tar;
	public char tnSplitSwitch;
	public char busRateBand;
	public String remoteOrHostType;
	public String alternateNpa;
	public String addrRmks1;
	public String addrRmks2;
	public String addrRmks3;
	public String addrRmks4;
	public String descAddrRmks1;
	public String descAddrRmks2;
	public String descAddrRmks3;
	public String descAddrRmks4;
	public char matchInd;
	public String lata;
	public String filler1;
	public String e911Sur;
	public String e911Exempt;
	public String e911Nrg;
	public char operSur4Ind;
	public char operSur16Ind;
	public String facsWireCenter;
	public String primaryLso;
	public String NbrOfNpaNxx;
	public com.sbc.gwsvcs.service.asonservice.interfaces.npaNxx_st npaNxx[];

	public ASONSagValidResp () {
	}
	public ASONSagValidResp (com.sbc.gwsvcs.service.asonservice.interfaces.comReplyHdr1_st comReplyHdr1, com.sbc.gwsvcs.service.asonservice.interfaces.comReplyHdr2_st comReplyHdr2, String raiCode, char sagAreaId, char alphaNumInd, String addressNameSag, String directional, String highAddrRange, String lowAddrRange, char oddEvenIndicator, String exchange, String centralOffice, String map, char rateBand, char rateZone, String zipCodeSag, String npa, String countyAbbrev, String municipality, String sagWireCenter, String communitySag, String state, char needBillAddrInd, char editAgainstLufFile, char needLocLevel1Ind, char needLocLevel2Ind, char needLocLevel3Ind, char needCommNameInd, char secondLineInd, char metroOptSvcInd, char omitCentralOfficeInd, char remarksInd, String lastAssignedHouseNumUsed, String cityAbbreviation, char populateCommNameInd, char alternateAddressInd, char lfacsDupAddressInd, String equipmentType, char analogOrDigitalType, String tar, char tnSplitSwitch, char busRateBand, String remoteOrHostType, String alternateNpa, String addrRmks1, String addrRmks2, String addrRmks3, String addrRmks4, String descAddrRmks1, String descAddrRmks2, String descAddrRmks3, String descAddrRmks4, char matchInd, String lata, String filler1, String e911Sur, String e911Exempt, String e911Nrg, char operSur4Ind, char operSur16Ind, String facsWireCenter, String primaryLso, String NbrOfNpaNxx, com.sbc.gwsvcs.service.asonservice.interfaces.npaNxx_st npaNxx[]) { 
		this.comReplyHdr1 = comReplyHdr1;
		this.comReplyHdr2 = comReplyHdr2;
		this.raiCode = raiCode;
		this.sagAreaId = sagAreaId;
		this.alphaNumInd = alphaNumInd;
		this.addressNameSag = addressNameSag;
		this.directional = directional;
		this.highAddrRange = highAddrRange;
		this.lowAddrRange = lowAddrRange;
		this.oddEvenIndicator = oddEvenIndicator;
		this.exchange = exchange;
		this.centralOffice = centralOffice;
		this.map = map;
		this.rateBand = rateBand;
		this.rateZone = rateZone;
		this.zipCodeSag = zipCodeSag;
		this.npa = npa;
		this.countyAbbrev = countyAbbrev;
		this.municipality = municipality;
		this.sagWireCenter = sagWireCenter;
		this.communitySag = communitySag;
		this.state = state;
		this.needBillAddrInd = needBillAddrInd;
		this.editAgainstLufFile = editAgainstLufFile;
		this.needLocLevel1Ind = needLocLevel1Ind;
		this.needLocLevel2Ind = needLocLevel2Ind;
		this.needLocLevel3Ind = needLocLevel3Ind;
		this.needCommNameInd = needCommNameInd;
		this.secondLineInd = secondLineInd;
		this.metroOptSvcInd = metroOptSvcInd;
		this.omitCentralOfficeInd = omitCentralOfficeInd;
		this.remarksInd = remarksInd;
		this.lastAssignedHouseNumUsed = lastAssignedHouseNumUsed;
		this.cityAbbreviation = cityAbbreviation;
		this.populateCommNameInd = populateCommNameInd;
		this.alternateAddressInd = alternateAddressInd;
		this.lfacsDupAddressInd = lfacsDupAddressInd;
		this.equipmentType = equipmentType;
		this.analogOrDigitalType = analogOrDigitalType;
		this.tar = tar;
		this.tnSplitSwitch = tnSplitSwitch;
		this.busRateBand = busRateBand;
		this.remoteOrHostType = remoteOrHostType;
		this.alternateNpa = alternateNpa;
		this.addrRmks1 = addrRmks1;
		this.addrRmks2 = addrRmks2;
		this.addrRmks3 = addrRmks3;
		this.addrRmks4 = addrRmks4;
		this.descAddrRmks1 = descAddrRmks1;
		this.descAddrRmks2 = descAddrRmks2;
		this.descAddrRmks3 = descAddrRmks3;
		this.descAddrRmks4 = descAddrRmks4;
		this.matchInd = matchInd;
		this.lata = lata;
		this.filler1 = filler1;
		this.e911Sur = e911Sur;
		this.e911Exempt = e911Exempt;
		this.e911Nrg = e911Nrg;
		this.operSur4Ind = operSur4Ind;
		this.operSur16Ind = operSur16Ind;
		this.facsWireCenter = facsWireCenter;
		this.primaryLso = primaryLso;
		this.NbrOfNpaNxx = NbrOfNpaNxx;
		this.npaNxx = npaNxx;

	}
}
