//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.20 at 02:19:21 AM EDT 
//


package com.att.lms.bis.service.ovals.model.avsqub.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cingular.csi.csi.namespaces.container._public.addressvalidationservicequalificationunifiedbillresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddressValidationServiceQualificationUnifiedBillResponse_QNAME = new QName("http://csi.cingular.com/CSI/Namespaces/Container/Public/AddressValidationServiceQualificationUnifiedBillResponse.xsd", "AddressValidationServiceQualificationUnifiedBillResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cingular.csi.csi.namespaces.container._public.addressvalidationservicequalificationunifiedbillresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvsqubResponse }
     * 
     */
    public AvsqubResponse createAddressValidationServiceQualificationUnifiedBillResponseInfo() {
        return new AvsqubResponse();
    }

    /**
     * Create an instance of {@link AvsqubResponse.ResultResponse }
     * 
     */
    public AvsqubResponse.ResultResponse createAddressValidationServiceQualificationUnifiedBillResponseInfoResultResponse() {
        return new AvsqubResponse.ResultResponse();
    }

    /**
     * Create an instance of {@link AvsqubResponse.DTVLocationProperties }
     * 
     */
    public AvsqubResponse.DTVLocationProperties createAddressValidationServiceQualificationUnifiedBillResponseInfoDTVLocationProperties() {
        return new AvsqubResponse.DTVLocationProperties();
    }

    /**
     * Create an instance of {@link AvsqubResponse.USPSDeliveryPointValidation }
     * 
     */
    public AvsqubResponse.USPSDeliveryPointValidation createAddressValidationServiceQualificationUnifiedBillResponseInfoUSPSDeliveryPointValidation() {
        return new AvsqubResponse.USPSDeliveryPointValidation();
    }

    /**
     * Create an instance of {@link AvsqubResponse.USPSDeliveryPointValidation.LocationProperties }
     * 
     */
    public AvsqubResponse.USPSDeliveryPointValidation.LocationProperties createAddressValidationServiceQualificationUnifiedBillResponseInfoUSPSDeliveryPointValidationLocationProperties() {
        return new AvsqubResponse.USPSDeliveryPointValidation.LocationProperties();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocation() {
        return new AvsqubResponse.SeviceOfferingFromLocation();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocation() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationOfferingServices() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResults() {
        return new AvsqubResponse.LocationMatchAvailabilityResults();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsAlternateLocationAvailabilityResults() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsAlternateLocationAvailabilityResultsLocation() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsAlternateLocationAvailabilityResultsLocationLocationList() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResults() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsDataProducts() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsDataProductsProductBandwidthDetails() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransport() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransportSubTransport() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationProperties() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocation() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationLocationList() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList();
    }

    /**
     * Create an instance of {@link AvsqubResponse.ResultResponse.AdditionalResult }
     * 
     */
    public AvsqubResponse.ResultResponse.AdditionalResult createAddressValidationServiceQualificationUnifiedBillResponseInfoResultResponseAdditionalResult() {
        return new AvsqubResponse.ResultResponse.AdditionalResult();
    }

    /**
     * Create an instance of {@link AvsqubResponse.DTVLocationProperties.Census }
     * 
     */
    public AvsqubResponse.DTVLocationProperties.Census createAddressValidationServiceQualificationUnifiedBillResponseInfoDTVLocationPropertiesCensus() {
        return new AvsqubResponse.DTVLocationProperties.Census();
    }

    /**
     * Create an instance of {@link AvsqubResponse.DTVLocationProperties.DealerDetails }
     * 
     */
    public AvsqubResponse.DTVLocationProperties.DealerDetails createAddressValidationServiceQualificationUnifiedBillResponseInfoDTVLocationPropertiesDealerDetails() {
        return new AvsqubResponse.DTVLocationProperties.DealerDetails();
    }

    /**
     * Create an instance of {@link AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.LACSInfo }
     * 
     */
    public AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.LACSInfo createAddressValidationServiceQualificationUnifiedBillResponseInfoUSPSDeliveryPointValidationLocationPropertiesLACSInfo() {
        return new AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.LACSInfo();
    }

    /**
     * Create an instance of {@link AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.PostalSupplementalData }
     * 
     */
    public AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.PostalSupplementalData createAddressValidationServiceQualificationUnifiedBillResponseInfoUSPSDeliveryPointValidationLocationPropertiesPostalSupplementalData() {
        return new AvsqubResponse.USPSDeliveryPointValidation.LocationProperties.PostalSupplementalData();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.Counties }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.Counties createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationCounties() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.Counties();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.WirelessMarket }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.WirelessMarket createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationWirelessMarket() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.WirelessMarket();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.Properties }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.Properties createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationProperties() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.Properties();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.ServiceExistForBANs }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.ServiceExistForBANs createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationOfferingServicesServiceExistForBANs() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.ServiceExistForBANs();
    }

    /**
     * Create an instance of {@link AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.CellSector }
     * 
     */
    public AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.CellSector createAddressValidationServiceQualificationUnifiedBillResponseInfoSeviceOfferingFromLocationLocationOfferingServicesCellSector() {
        return new AvsqubResponse.SeviceOfferingFromLocation.Location.OfferingServices.CellSector();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList.LocationDetails }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList.LocationDetails createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsAlternateLocationAvailabilityResultsLocationLocationListLocationDetails() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.AlternateLocationAvailabilityResults.Location.LocationList.LocationDetails();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.ProductList }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.ProductList createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsProductList() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.ProductList();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.AdditionalZipData }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.AdditionalZipData createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsAdditionalZipData() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.AdditionalZipData();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails.BandwidthData }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails.BandwidthData createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsDataProductsProductBandwidthDetailsBandwidthData() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.DataProducts.ProductBandwidthDetails.BandwidthData();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.NetworkTransportId }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.NetworkTransportId createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransportNetworkTransportId() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.NetworkTransportId();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.ProductList }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.ProductList createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransportProductList() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.ProductList();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.HighestHSIADetails }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.HighestHSIADetails createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransportHighestHSIADetails() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.HighestHSIADetails();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport.ProductList }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport.ProductList createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsTransportSubTransportProductList() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Transport.SubTransport.ProductList();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocationExtensions }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocationExtensions createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationPropertiesLocationExtensions() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocationExtensions();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocalNetworkServices }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocalNetworkServices createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationPropertiesLocalNetworkServices() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.LocalNetworkServices();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.ABFIntervalDetails }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.ABFIntervalDetails createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationPropertiesABFIntervalDetails() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.LocationProperties.ABFIntervalDetails();
    }

    /**
     * Create an instance of {@link AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList.LocationDetails }
     * 
     */
    public AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList.LocationDetails createAddressValidationServiceQualificationUnifiedBillResponseInfoLocationMatchAvailabilityResultsExactLocationAvailabilityResultsLocationLocationListLocationDetails() {
        return new AvsqubResponse.LocationMatchAvailabilityResults.ExactLocationAvailabilityResults.Location.LocationList.LocationDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvsqubResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://csi.cingular.com/CSI/Namespaces/Container/Public/AddressValidationServiceQualificationUnifiedBillResponse.xsd", name = "AddressValidationServiceQualificationUnifiedBillResponse")
    public JAXBElement<AvsqubResponse> createAddressValidationServiceQualificationUnifiedBillResponse(AvsqubResponse value) {
        return new JAXBElement<AvsqubResponse>(_AddressValidationServiceQualificationUnifiedBillResponse_QNAME, AvsqubResponse.class, null, value);
    }

}
