//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.06 at 02:01:52 PM PST 
//


package com.att.lms.bis.service.ovals.model.pavs.request1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for postalAddressValidationServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="postalAddressValidationServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conversationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maximumCASSAddressLineLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maximumAlternativeAddresses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://ovalgis.att.com/GIS/Namespaces/OVALSGIS/Types/Public/CommonDataModelPAV.xsd}USAUniversalAddressInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "postalAddressValidationServiceRequestType", namespace = "http://ovalgis.att.com/PostalAddressValidationRequest.xsd", propOrder = {
    "conversationId",
    "maximumCASSAddressLineLength",
    "maximumAlternativeAddresses",
    "address"
})
@XmlSeeAlso({
    PostalAddressValidationServiceRequest.class
})
public class PostalAddressValidationServiceRequestType {

    protected String conversationId;
    protected int maximumCASSAddressLineLength;
    protected Integer maximumAlternativeAddresses;
    @XmlElement(name = "Address")
    protected USAUniversalAddressInfo address;

    /**
     * Gets the value of the conversationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversationId() {
        return conversationId;
    }

    /**
     * Sets the value of the conversationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversationId(String value) {
        this.conversationId = value;
    }

    /**
     * Gets the value of the maximumCASSAddressLineLength property.
     * 
     */
    public int getMaximumCASSAddressLineLength() {
        return maximumCASSAddressLineLength;
    }

    /**
     * Sets the value of the maximumCASSAddressLineLength property.
     * 
     */
    public void setMaximumCASSAddressLineLength(int value) {
        this.maximumCASSAddressLineLength = value;
    }

    /**
     * Gets the value of the maximumAlternativeAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaximumAlternativeAddresses() {
        return maximumAlternativeAddresses;
    }

    /**
     * Sets the value of the maximumAlternativeAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaximumAlternativeAddresses(Integer value) {
        this.maximumAlternativeAddresses = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link USAUniversalAddressInfo }
     *     
     */
    public USAUniversalAddressInfo getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link USAUniversalAddressInfo }
     *     
     */
    public void setAddress(USAUniversalAddressInfo value) {
        this.address = value;
    }

}
